minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.119 || 4.0.20'
  - '@ai-sdk/openai@3.0.65 || 4.0.15'
  - ai@6.0.190 || 7.0.28
  - helmet@8.2.0
  - libphonenumber-js@1.13.3
  - '@ai-sdk/provider-utils@5.0.10'

minimumReleaseAge: 4320
strictDepBuilds: true
allowBuilds:
  sharp: true

overrides:
  chokidar: ^4.0.3